### PR TITLE
Sample of more standard drone.yml

### PR DESCRIPTION
**Pull request by josmo**
@tboerger What do you think of something like this to keep it simpler to not have typos in the images?

### CODE REVIEW

**Review by tboerger — APPROVED** [review]
Looks like a solid way to avoid any wrong repo pushs

**Comment by tboerger** [comment]
Do you add that also to the repos where we already merged the updated build process?

**Comment by bradrydzewski** [comment]
this won't work ... `DRONE_REPO_NAME` is in `{owner}/{name}` format

**Comment by bradrydzewski** [comment]
edit `CI_REPO_NAME` is in `{owner}/{name}` format. `DRONE_REPO_NAME` is fine. But personally I would not recommend using environment variables until they are finalized for 1.0. It is possible there could be some changes, which would end up resulting in a bunch of re-work for the plugins using them.

**Pull request merged**
